### ISSUE TITLE
doesn't work anymore ??

### ISSUE THREAD

**Issue by ghost** [DoubleHub/cyberdrop-downloader#2]
maybe I'm doing it wrong because I have zero idea how to use these programs on github that require me to download python and who else knows what, but I followed the instructions after installing GitHubDesktop and some other GitBash thing it asked me to get, as well as Go.

But I get this error trying to follow the building commands https://i.gyazo.com/8932a0323ece6e59f6c0e46a96fe2259.png

**Comment by giovanni-orciuolo** [comment]
Since this Go program is very simple and barebones, I do not use Go modules to handle dependencies. This means that you gotta install said dependencies manually, as described in the readme file of the project.
In short, just run this command in the terminal:
`
go get golang.org/x/net/html gopkg.in/matryer/try.v1 github.com/vbauerster/mpb
`

Then build the exe:
`go build main.go`

Tell me if it works ^^

**Comment by pewpewpewpewpewpewpewpew** [comment]
I was receiving the same error, and couldn't get this to compile until I ran the command from [this page](https://blog.golang.org/go116-module-changes):

`go env -w GO111MODULE=auto`
